import URI from "vscode-uri";
import { TypeSystemDefinitionNode, TypeSystemExtensionNode, DefinitionNode, GraphQLSchema } from "graphql";
import { TextDocument, NotificationHandler, PublishDiagnosticsParams, Position } from "vscode-languageserver";
import { GraphQLDocument } from "../document";
import type { LoadingHandler } from "../loadingHandler";
import { ApolloConfig, ClientConfig, ServiceConfig } from "../config";
import { GraphQLSchemaProvider, SchemaResolveConfig } from "../providers/schema";
import { ApolloEngineClient, ClientIdentity } from "../engine";
import type { ProjectStats } from "src/messages";
export declare type DocumentUri = string;
interface GraphQLProjectConfig {
    clientIdentity?: ClientIdentity;
    config: ClientConfig | ServiceConfig;
    configFolderURI: URI;
    loadingHandler: LoadingHandler;
}
export declare abstract class GraphQLProject implements GraphQLSchemaProvider {
    schemaProvider: GraphQLSchemaProvider;
    protected _onDiagnostics?: NotificationHandler<PublishDiagnosticsParams>;
    private _isReady;
    private readyPromise;
    protected engineClient?: ApolloEngineClient;
    private needsValidation;
    protected documentsByFile: Map<DocumentUri, GraphQLDocument[]>;
    config: ApolloConfig;
    schema?: GraphQLSchema;
    private fileSet;
    private rootURI;
    protected loadingHandler: LoadingHandler;
    protected lastLoadDate?: number;
    constructor({ config, configFolderURI, loadingHandler, clientIdentity, }: GraphQLProjectConfig);
    abstract get displayName(): string;
    protected abstract initialize(): Promise<void>[];
    abstract getProjectStats(): ProjectStats;
    get isReady(): boolean;
    get engine(): ApolloEngineClient;
    get whenReady(): Promise<void>;
    updateConfig(config: ApolloConfig): Promise<void>[];
    resolveSchema(config: SchemaResolveConfig): Promise<GraphQLSchema>;
    resolveFederatedServiceSDL(): Promise<string | void>;
    onSchemaChange(handler: NotificationHandler<GraphQLSchema>): import("../providers/schema").SchemaChangeUnsubscribeHandler;
    onDiagnostics(handler: NotificationHandler<PublishDiagnosticsParams>): void;
    includesFile(uri: DocumentUri): boolean;
    allIncludedFiles(): string[];
    scanAllIncludedFiles(): Promise<void>;
    fileDidChange(uri: DocumentUri): void;
    fileWasDeleted(uri: DocumentUri): void;
    documentDidChange(document: TextDocument): void;
    checkForDuplicateOperations(): void;
    private removeGraphQLDocumentsFor;
    protected invalidate(): void;
    private validateIfNeeded;
    private getRelativeLocalSchemaFilePaths;
    abstract validate(): void;
    clearAllDiagnostics(): void;
    documentsAt(uri: DocumentUri): GraphQLDocument[] | undefined;
    documentAt(uri: DocumentUri, position: Position): GraphQLDocument | undefined;
    get documents(): GraphQLDocument[];
    get definitions(): DefinitionNode[];
    definitionsAt(uri: DocumentUri): DefinitionNode[];
    get typeSystemDefinitionsAndExtensions(): (TypeSystemDefinitionNode | TypeSystemExtensionNode)[];
}
export {};
//# sourceMappingURL=base.d.ts.map